name: Make Linux C++

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  make:
    runs-on: ubuntu-latest
    env:
      CC:  gcc-10
      CXX: g++-10
    steps:
    - uses: actions/checkout@v2
    - name: Check make
      run: make --version
    - name: Check system
      run: make detect_port
    - name: Check C++
      run: make detect_cc
    - name: Build C++
      run: make cc JOBS=4
    - name: Test C++
      run: make test_cc
    - name: Install
      run: make install_cc DESTDIR=install
